spring.application.name=ToDo
spring.datasource.url=jdbc:postgresql://localhost:5432/ToDo
spring.datasource.username=postgres
spring.datasource.password=sakshi25
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false
